---
title: "Code Book for the Tidy Data of the Course Project (Getting and Cleaning Data Class)."
author: "Igor Telezhinsky"
date: "2015-11-22"
output:
  html_document:
    keep_md: yes
---

## Project Description
The purpose of this project is to demonstrate the ability to collect, work with, and clean a data set.
The goal is to prepare tidy data that can be used for later analysis.

##Study design and data processing

###Collection of the raw data

The data for the project represent data collected from the accelerometers 
of the Samsung Galaxy S2 smartphones attached to the waist bands of 30 people
and recording their activity throughout the day. The data can be download from

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

A full description is available at the site where the data was originally obtained:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

###Notes on the original (raw) data 
The original data contains two data sets: test and training raw data sets stored in several files. Each of these data set contains besides raw also processed and filtered data that is not used in the current project. The files used to obtain tidy data are:


1. `README.txt`          -- general info about data set
2. `features_info.txt`   -- description variable names
3. `features.txt`        -- columns names in data files (variables)
4. `activity_labels.txt` -- activities code-name connection
5. `X_test.txt`          -- test data set
6. `y_test.txt`          -- activity codes in the test data set
7. `subject_test.txt`    -- subject (a person given a number) performing a given activity in the test data set
8. `X_train.txt`         -- training data set
9. `y_train.txt`         -- activity codes in the training data set
10. `subject_train.txt`   -- subject (a person given a number) performing a given activity in the training data set.

##Creating the tidy datafile

###Guide to create the tidy data file

To create the tidy data file source `run_analysis.R` script and execute `run_analysis(work_dir,outfile,data_dir)` function, where
`work_dir` is the working directory path, `outfile` is the output file name and `data_dir` is where the raw data will be extracted
from the automatically downloaded zip archive. Both last arguments are relative to the working directory path. At least `work_dir`
must be specified. Other variables are optional with the default values set to 
`outfile="tidy_data.txt"` and `data_dir="RawData"`. For particular example see README file.

###Cleaning of the data steps

The `run_analysis()` function of the `run_analysis.R` script goes through the following steps:

1. downloads the raw data
2. unpacks the raw data
3. prepares the data set as it should be in Step 4 of the Project Task
    - reads activity names
    - reads raw data variables' names
    - reads test data files and introduces descriptive variable names
    - reads training data files and introduces descriptive variable names
    - gets column indeces of various *mean* and *std* quantities in raw data
    - selects *mean* and *std* columns from the raw data sets (test and training) and combines these data into a single data frame
    - introduces descriptive activity names to this data frame
4. melts Step 4 data set with `id=c("Activity","Subject")`
5. casts the molten data set and computes mean for `variables`
6. renames the first column to "Activity.Subject"
7. writes down the tidy data set.

##Description of the variables in the tidy_data.txt (outfile)
The file contains the tidy data set of 180 rows by 80 columns. The following summary is compiled with

```{r}
source('./run_analysis.R')
tidy<-read_tidy("tidy_data.txt")
str(tidy)
```

###Variable 1
Subject.Activity is a factor variable of 180 levels corresponding to 30 subjects with 6 activities each.

###Variables 2-80
The numerical variables are normalized to the range between -1 to 1 and are therefore dimensionless. Each variable represents the average of more than 10000 observations for each Subject and each Activity. The explanation of variable names can be found in *features_info.txt* file coming with raw data.

##Sources
This CodeBook was prepared with the template available at
https://gist.github.com/JorisSchut/dbc1fc0402f28cad9b41
